# Generated by Django 2.1.5 on 2019-04-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAT_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_use',
        ),
    ]
