# Generated by Django 2.1.5 on 2019-05-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAT_project', '0002_remove_question_is_use'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('field', 'dimension_text')},
        ),
    ]
