# Generated by Django 2.1.5 on 2019-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT_project', '0003_auto_20190504_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='dimension_text',
            field=models.CharField(max_length=32, verbose_name='维度'),
        ),
    ]
