# Generated by Django 2.1.5 on 2019-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT_project', '0005_auto_20190504_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=128, verbose_name='题目'),
        ),
    ]
